### ISSUE TITLE
rt.cpan.org deprecation

### ISSUE THREAD

**Issue by jonasbn** [jonasbn/perl-date-holidays-super#6]
Remove rt.cpan.org references

**Comment by peternewman** [comment]
FYI as you may have seen it hasn't actually gone away in the end:
https://news.perlfoundation.org/post/rt-cpan-org-upgraded

**Comment by jonasbn** [comment]
hi @peternewman 

Yes I saw, I think I am going to shift anyway, I like have the issue reports closer to the code base.

**Comment by peternewman** [comment]
Yeah fair enough, I can certainly see the benefits of that with the link integration.

There is some stuff you can do from GitHub, but it seems that's only for commercial organisations.
